Add cvar: mp_weapon_knockback
s1lentq/ReGameDLL_CS pull request #707
Opened 2021-11-12 13:09 UTC by justgo97

Allows to disable engine knockback behavior, useful for mods where they don't want this feature or want to implement their own knockback system like zombie mods...etc

2021-11-12 15:44 UTC, justgo97 commented
@Vaqtincha why the downvote? 👀

2021-11-12 17:16 UTC, hajimura commented
Because recently some people makes shitty pull requests and this is one of them 🤡. tf is this? Who needs this? If you're interested in this idea, do it in your fork of the project or via amxx

2021-11-12 18:31 UTC, justgo97 commented
This is a hardcoded thing in the regamedll, you can't reliably change it in amxx...

> Because recently some people makes shitty pull requests and this is one of them 🤡. tf is this? Who needs this? If you're interested in this idea, do it in your fork of the project or via amxx

2021-11-12 18:42 UTC, hajimura commented
TakeDamage_Pre hook -> get_entvar(id, var_velocity, m_iVelocity)
TakeDamage_Post hook -> set_entvar(id, var_velocity, m_iVelocity)

2021-11-12 20:06 UTC, Vaqtincha commented
@justgo97 Make it more functional and not just on / off. Or is it better to add api (player member) Ps: I would go even longer and make the slowdown (knockback) from the ammo type.

2021-11-13 09:04 UTC, justgo97 commented
> TakeDamage_Pre hook -> get_entvar(id, var_velocity, m_iVelocity) TakeDamage_Post hook -> set_entvar(id, var_velocity, m_iVelocity)

That's not a clean method especially when you have plugins constantly checking/modifiying velocity, try to constantly print the velocity value and you will understand what I mean, not changing the velocity in the first place is cleaner.

2021-11-13 09:06 UTC, justgo97 commented
> @justgo97 Make it more functional and not just on / off. Or is it better to add api (player member)
> 
> Ps: I would go even longer and make the slowdown (knockback) from the ammo type.

That's a good idea, But maybe in the future, for now, I just want a clean method to disable the engine from messing with the player velocity and the cvar is the only possible way to do it.

2021-11-13 16:36 UTC, fl0werD commented
It's useful for zombie modes, can you add api for 170?

2021-11-14 10:32 UTC, justgo97 commented
> It's useful for zombie modes, can you add api for 170?

Well probably, but you can with this cvar disable the engine knockback and implement your own system in amxx especially if you have custom weapons and stuff.

2021-11-14 12:53 UTC, Vaqtincha commented
No, it doesn't work that way. You have to make it more versatile.
But it's still better to add a memeber.

2021-11-15 09:22 UTC, justgo97 commented
> No, it doesn't work that way. You have to make it more versatile. But it's still better to add a member.

Well, That can be done in another PR, Also maintainers don't seem much active so complex PRs might be not a good idea at this time...

2021-11-15 11:20 UTC, Vaqtincha commented
@justgo97 Don't waste your precious time on this. They don't take your pr. Better develop your fork.

2021-11-16 03:25 UTC, wopox1337 requested changes

2021-11-16 03:25 UTC, wopox1337 commented on regamedll/dlls/game.cpp
> +cvar_t weapon_knockback                 = { "mp_weapon_knockback", "1", 0, 0.0f, nullptr };
```suggestion
cvar_t weapon_knockback                  = { "mp_weapon_knockback", "1", 0, 0.0f, nullptr };
```

2021-11-16 03:25 UTC, wopox1337 commented on regamedll/dlls/player.cpp
> +				if (weapon_knockback.value != 0.0)
```suggestion
				if (weapon_knockback.value)
```

2021-11-16 03:25 UTC, wopox1337 commented on README.md
> +| mp_weapon_knockback                | 0       | 0   | 1            | When set weapons will have the default knockback.<br/>`0` disabled <br/>`1` enabled |
```suggestion
| mp_weapon_knockback                | 0       | 0   | 1            | When set, weapons will have the default knockback.<br/>`0` disabled <br/>`1` enabled |
```

2021-11-16 03:25 UTC, wopox1337 commented on dist/game.cfg
> +// When set weapons will have the default knockback.
```suggestion
// When set, weapons will have the default knockback.
```

2021-11-16 07:43 UTC, justgo97 commented
> @justgo97 Don't waste your precious time on this. They don't take your pr. Better develop your fork.

Be patient 😄

2021-11-16 07:58 UTC, Vaqtincha commented
@justgo97 Don't get too excited. He is a rotten man. Trying to prove he exists here.

2021-11-16 08:06 UTC, Vaqtincha commented
Наверняка принимает этот бесполезный и не функциональный пр. Но это не оправдывает его неадекватность и высокомерность к отношению другим людям (ведь они потратили время). Отмазки "У миня нет вримени" да нет пару минут чтобы кликать энтер.

2021-11-16 16:11 UTC, justgo97 commented
> @justgo97 Don't get too excited. He is a rotten man. Trying to prove he exists here.

Calm down, Your behavior is really toxic, This PR or others are not a high priority, It's not a critical bug fix or something.

2021-11-16 17:35 UTC, Vaqtincha commented
@justgo97 Even my critical bug fixes do not want to accept. Clown.

2021-11-17 09:41 UTC, wopox1337 commented
1) It would be nice to adjust the multiplier (`0.0 .. 1.0`) rather than just the switch (`true .. false`).
2) This implementation is too simple, and does not leave the flexibility to handle a wider range of tasks. More flexible use should be considered.
3) Perhaps a better solution would be to put the entire code section into a separate function.
https://github.com/s1lentq/ReGameDLL_CS/blob/e613735900b4dca9a7fb094771653f50d18cdc9c/regamedll/dlls/player.cpp#L1144-L1155 
([or even more](https://github.com/s1lentq/ReGameDLL_CS/blob/e613735900b4dca9a7fb094771653f50d18cdc9c/regamedll/dlls/player.cpp#L1090-L1159))

2021-11-17 10:40 UTC, justgo97 commented
I guess it's better to separate that into multiple PRs, Unfortunately, Currently I don't have the time to make more changes and test each case, I might only do minor and easy to test changes for now.

> 1. It would be nice to adjust the multiplier (`0.0 .. 1.0`) rather than just the switch (`true .. false`).
> 2. This implementation is too simple, and does not leave the flexibility to handle a wider range of tasks. More flexible use should be considered.
> 3. Perhaps a better solution would be to put the entire code section into a separate function.
>    https://github.com/s1lentq/ReGameDLL_CS/blob/e613735900b4dca9a7fb094771653f50d18cdc9c/regamedll/dlls/player.cpp#L1144-L1155
>    
>    ([or even more](https://github.com/s1lentq/ReGameDLL_CS/blob/e613735900b4dca9a7fb094771653f50d18cdc9c/regamedll/dlls/player.cpp#L1090-L1159))

2022-02-06 18:18 UTC, RauliTop commented
It will be good to have an option for disable this and apply our full-customized knockback system.

Also, I don't understand that 300 velocity magical number
and
m_flVelocityModifier = 0.65f;

why is inside there and not out that check?

2022-02-08 13:08 UTC, RauliTop commented
The implementation is too simple, but we really need this to disable CS default knockback system and apply our own.
Probably, instead of a cvar on/off, will be better a cvar to change that * 170 multiplier. Value 0 will be marked as off.

We can't have flexibility, having flexibility will make change large pieces of CS code, and it's not necessary because we can do it with plugins.
Why? knockback on CS is not always applied. It depends on:
- ShouldDoLargeFlinch (player ducking or not, some weapons/body part hit hasn't got knockback)
- Velocity < 300

So, please @wopox1337 reconsider this feature.

2023-01-27 22:11 UTC, closed without merging