Update func_vehicle for multiplayer. Added mp_legacy_vehicle_block cvar.
s1lentq/ReGameDLL_CS pull request #737
Opened 2022-03-15 12:28 UTC by UnrealKaraulov

2022-03-15 13:24 UTC, UnrealKaraulov commented
@s1lentq Хотим на сервер карт с машинами залить типа big_city2 всем нравятся карты, даже пусть физика у машин не самая лучшая))) 

но вот некоторые проблемы сильно мешают использовать такие карты на сервере!

В общем на картах с машинами невозможно играть по двум причинам...

1 - это убийство своих. 
2 - убийство врагов без отображения кила. 

Тут все решается. 
Записал два видео.

2022-03-15 13:25 UTC, wopox1337 requested changes

2022-03-15 13:27 UTC, UnrealKaraulov commented
Так же если заметили отключил m_pDriver = nullptr, что это дает, видно на последнем видео.

2022-03-15 13:37 UTC, wopox1337 commented
> Так же если заметили отключил m_pDriver = nullptr когда игрок отключает управление машиной, что это дает, видно на последнем видео.

I am not sure that these edits will be the correct behavior for the entity.  Because, in actuality, the entity ALWAYS does not have a driver after the player has left the vehicle. And this is the correct behavior for GameDLL. 

If you want the gameplay to consider a kill from the vehicle after the player has left it, you need to handle this as a specific case.

2022-03-15 13:44 UTC, UnrealKaraulov commented
> > Так же если заметили отключил m_pDriver = nullptr когда игрок отключает управление машиной, что это дает, видно на последнем видео.
> 
> I am not sure that these changes will be the correct behavior for the entity. Because, in actuality, the entity ALWAYS does not have a driver after the player has left the vehicle. And this is the correct behavior for GameDLL.
> 
> If you want the gameplay to consider a kill from the vehicle after the player has left it, you need to handle this as a specific case.


In multiplayer need known who is latest driver for give kill him.
Now I fix default behavior, added check for behavior cvar.

2022-03-15 14:15 UTC, UnrealKaraulov commented
@[wopox1337](https://github.com/wopox1337) Now all okay or need some more changes ?

2022-03-15 14:17 UTC, hajimura commented
> but m_pDriver is not nullptr!



> we could add has_disconnected check

2022-03-15 14:20 UTC, wopox1337 commented
Waiting for @s1lentq review

2022-03-15 14:24 UTC, hajimura commented
> this class not deleted after player disconnect?

Yep. Slots that were released after player disconnect are still has CBasePlayer class and he updates after player connect

2022-03-15 14:26 UTC, UnrealKaraulov commented
@hajimura if player disconnected, but in this time, connected another player ?

2022-03-15 14:31 UTC, hajimura commented
🚢

2022-03-16 13:37 UTC, UnrealKaraulov reviewed
I think all okay

2022-03-17 11:13 UTC, wopox1337 commented
The new functionality needs to be introduced in a different way. At least this way: 
```cpp
  CFuncVehicle::m_hLastDriver;
  EntityHandle<CBaseEntity> m_hLastDriver;
```

and need to think better about the CVar name

2022-03-17 11:13 UTC, closed without merging

2022-03-17 11:28 UTC, UnrealKaraulov commented
Да и так сойдет, в оригинале все как-то работает и не падает)

2022-03-17 11:30 UTC, UnrealKaraulov commented
Да я уже в плагине сделал все так как тут пока дождешься чего-нибудь.... Хочешь сам доделывай мне этот пулреквест больше не нужен)

2022-03-17 12:16 UTC, UnrealKaraulov commented
> The new functionality needs to be introduced in a different way. At least this way:
> 
> ```c++
>   CFuncVehicle::m_hLastDriver;
>   EntityHandle<CBaseEntity> m_hLastDriver;
> ```
> 
> and need to think better about the CVar name

ну это скажи тому кто делал этот vehicle.cpp файл, оно изначально так было я ничего не менял.

2022-03-17 12:18 UTC, UnrealKaraulov commented
Да ладно закроем тему все равно уже сделал в отдельном плагине https://c-s.net.ua/forum/topic92614.html#entry1150161 где все работает так же и даже лучше и не надо ждать пока там переменные какие-то случаться  ) Удалил форк если тема интересна надо делай сам мне лень :)