Add cvar: mp_give_c4_frags
s1lentq/ReGameDLL_CS pull request #776
Opened 2022-10-02 14:14 UTC by 666JuL

2022-10-02 14:45 UTC, wopox1337 commented
I propose to make not a Boolean switch, but a CVar with the number of frags for the actions of the bomb.

`mp_give_c4_frags "3"`

2022-10-02 14:52 UTC, abecee commented
> I propose to make not a Boolean switch, but a CVar with the number of frags for the actions of the bomb.
> 
> ```cpp
> mp_give_c4_frags "3"
> mp_give_c4_frags "-10"
> mp_give_c4_frags "0"
> ```

Yep..this will be more useful then 0 and 1 command. For me i want to change the value's frags with wich number i want.

2022-10-08 16:43 UTC, wopox1337 requested changes

2022-10-08 16:43 UTC, wopox1337 commented on regamedll/dlls/game.cpp
> +cvar_t give_c4_frags                     = { "mp_give_c4_frags", "3", 0, 0.0f, nullptr };
```suggestion
cvar_t give_c4_frags                     = { "mp_give_c4_frags", "3", 0, 3.0f, nullptr };
```

2022-10-08 16:43 UTC, wopox1337 commented on dist/game.cfg
> +// When set, players can receive credits for defusing or exploding the bomb.
```suggestion
// How many bonuses (frags) will get the player who defused or exploded the bomb.
```

2022-10-08 16:43 UTC, wopox1337 commented on README.md
> +| mp_give_c4_frags               | 3       | -   | -            | When set, players can receive credits for defusing or exploding the bomb. |
```suggestion
| mp_give_c4_frags               | 3       | -   | -            | How many bonuses (frags) will get the player who defused or exploded the bomb. |
```

2022-10-08 16:43 UTC, wopox1337 approved these changes

2022-10-08 17:00 UTC, wopox1337 approved these changes

2022-10-08 17:17 UTC, wopox1337 approved these changes

2022-10-08 17:17 UTC, wopox1337 commented on regamedll/dlls/ggrenade.cpp
> +				m_pBombDefuser->pev->frags += give_c4_frags.value;
```suggestion
				m_pBombDefuser->pev->frags += (int)give_c4_frags.value;
```

2022-10-08 17:22 UTC, abecee commented
Will be this added in the next update ?

2022-10-08 17:32 UTC, merged

2022-10-09 04:05 UTC, Vaqtincha commented
The name cvar is inaccurate and incomprehensible.

2022-10-09 10:21 UTC, wopox1337 commented
@Vaqtincha @etojuice 😒
If anyone has suggestions for better naming - happy to accept, I will correct.

2023-02-21 02:59 UTC, deprale commented
> and "not a hint about the exploder" If anyone has suggestions for better naming - happy to accept, I will correct.
// How many points(frags) will the player be awarded for completing the objective (defuse/explode c4)
// 3 - (default behaviour)
//
// Default value: "3"
mp_objective_bonus 3

2023-02-21 04:43 UTC, wopox1337 commented
> mp_objective_bonus 3

Map objective can be different. de_, cs_, es_ and etc...

2023-02-21 10:22 UTC, deprale commented
>  > mp_objective_bonus 3
> 
> Map objective can be different. de_, cs_, es_ and etc...
> 
> 
> 

Yes, objective bonus sounds good then no? Because it is universal, only need to change the wording a little bit in the description to not only include c4.

'''Complete the objective - 
Defuse/plant(de)
Save VIP (as)
Save Hostages (cs)'''

I thought about different game modes but didn't check what the actual commit do, I just supposed it changed C4 score behaviour based on the cvar name 😅

2023-02-21 10:25 UTC, wopox1337 commented
https://github.com/s1lentq/ReGameDLL_CS/blob/d8702df5482d8945dff4ef5005261ffbc8b29343/regamedll/dlls/ggrenade.cpp#L1443

- that PR refers only to bomb bonus